apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: frontend

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cache
  name: cache
  namespace: frontend
spec:
  containers:
  - image: library/redis:3.2
    name: cache
    ports:
    - containerPort: 6379
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
