apiVersion: v1
kind: Namespace
metadata:
  name: resources

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
  namespace: resources
spec:
  containers:
  - args:
    - pod-resources
    image: nginx
    name: pod
    resources:
      requests:
         cpu: 300m
         memory: 1Gi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
