apiVersion: v1
data:
  password: bWFjaDU=
  username: dHJpeGll
kind: Secret
metadata:
  creationTimestamp: null
  name: service-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: secretservice
  name: secretservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secretservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: secretservice
    spec:
      containers:
      - image: alpine
        name: alpine
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/service-secret
          readOnly: true
        resources: {}
      volumes:
      - name: secret-volume
        secret:
          secretName: service-secret
          items:
          - key: password
            path: password
          - key: username
            path: username
status: {}
