apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: loop
  name: loop
spec:
  containers:
  - image: busybox
    name: loop
   # command: ["sh", "-c", "i=1; while [ $i -le ]; do echo \"welcome $i times\"; i=$((i+1)); done"]
   #  command: ["sh", "-c", "i=1; while true; do echo \"welcome $i times\"; i=$((i+1)); sleep 1; done"]
    command: ["sh", "-c", "i=1; while true; do echo \"$(date) - welcome $i times\"; i=$((i+1)); sleep 1; done"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
