apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: temppod
  name: temppod
  namespace: ckad1
spec:
  containers:
  - image: busybox
    name: temppod
    command:
    - wget
    - "-O"
    - "/dev/null"
    - "http://10.1.2.72:80"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
