apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: custom-cmd
  name: custom-cmd
spec:
  containers:
  - args:
    - bin/sh
    - -c
    - top-analyzer -all
    image: busybox
    name: custom-cmd
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
