apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: consume
  name: consume
spec:
  containers:
  - image: nginx
    name: consume
    env:
    - name: api_endpoint
      valueFrom:
       configMapKeyRef:
         name: ext-service-cm
         key: api_endpoint
    - name: username
      valueFrom:
       configMapKeyRef:
         name: ext-service-cm
         key: username 
    volumeMounts:
    - name: ext-service-secret-vol
      mountPath: /var/app
    resources: {}
  dnsPolicy: ClusterFirst
  volumes:
  - name: ext-service-secret-vol
    secret:
     secretName: ext-service-secret
  restartPolicy: Always
status: {}
