apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: monitoring


---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sa-monitoring-pod
  name: sa-monitoring-pod
spec:
  serviceAccountName: monitoring
  containers:
  - image: alpine
    name: sa-monitoring-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
