apiVersion: v1
kind: Namespace
metadata:
  name: project-corvette

---
apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: secret-resource
  namespace: project-corvette
spec:
  hard:
    count/secrets: "1"
status: {}
