apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
 containers:
  - image: nginx
    name: nodejs
    ports:
    - containerPort: 3000
      name: nodejs-port
    readinessProbe:
     httpGet:
       path: /
       port: nodejs-port
     initialDelaySeconds: 2
    livenessProbe:
     httpGet:
       path: /
       port: nodejs-port
     initialDelaySeconds: 5
   